# Generated by Django 4.2.11 on 2024-04-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minifacebook', '0003_poke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
